require 'capistrano/setup'
require 'capistrano/deploy'

require 'airbrake/capistrano3'
require 'capistrano-db-tasks'
require 'capistrano3/unicorn'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
#require 'capistrano/sidekiq'

require 'openteam/capistrano/tasks'
