after  'deploy',            'deploy:tagging:create'
after  'deploy:publishing', 'unicorn:restart'
after  'unicorn:restart',   'airbrake:deploy'
before 'deploy:cleanup',    'deploy:tagging:clean'
after  'sunspot:pull',      'sunspot:reload'
after  'sunspot:clear',     'sunspot:reload'
