require "openteam/capistrano/dependencies"
require "openteam/capistrano/hooks"
require "openteam/capistrano/setup_common"
require "openteam/capistrano/setup_deploy"
require "openteam/capistrano/setup_git"
require "openteam/capistrano/subscriber"
require "openteam/capistrano/tagging"
